### ISSUE TITLE
404 in Example URL

### ISSUE THREAD

**Issue by Myer** [NetAppDocs/contribute#16]
Page: [Style guide for NetApp docs](https://docs.netapp.com/us-en/contribute/style.html)

In the "Use visuals as much as possible" section, the "Example 1" link is not working (404 File not found): https://docs.netapp.com/us-en/occm/concept_accounts_and_permissions.html

**Comment by netapp-bcammett** [comment]
Thank you for catching this error! I fixed the link, which had changed.

Thanks again for your feedback.

Regards,
Ben
