### ISSUE TITLE
Graphic within the text looks too much like, well... text

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/contribute#18]
Page: [AsciiDoc reference](https://docs.netapp.com/us-en/contribute/asciidoc_syntax.html)

On this page, there is a graphic that contains text that says "View information in the NetApp HCI Doc Center."

I got confused and thought that this was text because the graphic isn't offset in any way.

Please consider creating a more visual distinction. Thanks.

**Comment by netapp-bcammett** [comment]
Thanks for the feedback. I agree 100%

With that in mind, I updated the image to include a border and I also added explanatory intro text:
https://docs.netapp.com/us-en/contribute/asciidoc_syntax.html#images-with-links

Let me know what you think.
