### ISSUE TITLE
Less or Fewer?

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/contribute#19]
Page: [Style guide for NetApp docs](https://docs.netapp.com/us-en/contribute/style.html)

Okay, so maybe I'm just an old curmudgeon (wait, don't answer that!), but I believe "Use less words" should be "Use fewer words." No?

**Comment by netapp-bcammett** [comment]
Dear old curmudgeon,

You're right. It should be "fewer." Here's one source that confirms:
https://www.grammarly.com/blog/fewer-vs-less/

The content has been updated.
