### ISSUE TITLE
Clarification needed for image notation

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/contribute#25]
Page: [AsciiDoc reference](https://docs.netapp.com/us-en/contribute/asciidoc_syntax.html)

According to the AsciiDoctor reference, the syntax for an inline graphic uses a single colon while the double is used for graphics on their own line.

https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#images

This corresponds to what works/doesn't with the AsciiDoc Preview in Atom - an inline image doesn't display if there are two colons.

**Comment by netapp-bcammett** [comment]
Little late here, but I updated the syntax notation for images:
https://docs.netapp.com/us-en/contribute/asciidoc_syntax.html#images

Thanks again,
Ben
