### ISSUE TITLE
Reused content not appearing in PDF

### ISSUE THREAD

**Issue by netapp-soumikd** [NetAppDocs/contribute#35]
Page: [AsciiDoc reference](https://docs.netapp.com/us-en/contribute/asciidoc_syntax.html#content-reuse)

As per the instruction, if we use "include::_include/<filename>.adoc[]", the reused content appears in the HTML file but it does not appear in the PDF.

![image](https://user-images.githubusercontent.com/64966556/121939728-efe63100-cd6a-11eb-839e-08a9caf51232.png)

When I changed the syntax to "include::../_include/<filename>.adoc[]", content is appearing in both HTML and PDF.

Should this syntax be updated?

**Comment by netapp-bcammett** [comment]
@akseldavis, can you please confirm the correct syntax? I'm assuming it changed due to PDF tweaks?
