### ISSUE TITLE
Add reference for "include" syntax

### ISSUE THREAD

**Issue by netapp-rlithman** [NetAppDocs/contribute#36]
Page: [AsciiDoc reference](https://docs.netapp.com/us-en/contribute/asciidoc_syntax.html)

I recently learned about using an include folder within a repo, but I don't know the syntax for linking to include folder files within an .adoc file. Could you please add this referential syntax to our Asciidoc cheat sheet, please?  

Thanks!
Rachel

**Comment by netapp-bcammett** [comment]
Hi Rachel,

includes are documented in the following section:
https://docs.netapp.com/us-en/contribute/asciidoc_syntax.html#content-reuse

Thanks,
Ben

**Comment by netapp-rlithman** [comment]
Awesome! Thanks, Ben!
