### ISSUE TITLE
Distinction between : and :: 

### ISSUE THREAD

**Issue by juliantap** [NetAppDocs/contribute#42]
Page: [AsciiDoc reference](https://docs.netapp.com/us-en/contribute/asciidoc_syntax.html)

Hi Ben, do you think we should call out the difference between using ":" and "::" on this page? I hadn't even noticed until Katie pointed it out. Tom provided the https://docs.asciidoctor.org/asciidoc/latest/macros/images/ reference.

**Comment by netapp-bcammett** [comment]
Hi Julia,

Thank you for submitting this issue. I updated the syntax notation for images:
https://docs.netapp.com/us-en/contribute/asciidoc_syntax.html#images

Thanks again,
Ben
