### ISSUE TITLE
generate fr and de - 498

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/contribute#52]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by ntap-bmegan** [comment]
@netapp-gudugunti - I've kicked this one off and added it to the project.

**Comment by ntap-bmegan** [comment]
The French site deployed correctly but German seems to be hung. Investigating.

**Comment by ntap-bmegan** [comment]
German build failed initially. Re-ran and it succeeded. 

[failed build](https://github.com/NetAppDocs/contribute.de-de/actions/runs/3461408135/attempts/1)

**Comment by netapp-gudugunti** [comment]
Applied branch protection rules and labels.

**Comment by ntap-bmegan** [comment]
Additional TOT: build debug, 3 minutes

**Comment by netapp-gudugunti** [comment]
Total TOT: 6 minutes
